layout_spectrum: 0
typography_spectrum: 0.297491
color:
  saturation: 0.8844703
  lightness: 0.8527004
  brandStrength: 0.7575023
  rhythmicContrast: 0.7598579
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Mechanics of Bliss
